version: "3.5"
services:
  websocket:
    image: golang:1.20-alpine
    restart: always
    container_name: websocket-4-inline-server
    working_dir: /app
    volumes: 
      - .:/app
    command: go run /app/cmd/server --port 6060 --client /app/client
    ports:
      - 6060:6060


